name: minecraft_fun
version: '1.0-SNAPSHOT'
main: me.itzorg.minecraft_fun
api-version: 1.18
authors: [ ItzOrg ]
description: My second MC Plugin
commands:
  nick:
    description: Makes you a noob
    usage: /<command>
  gui:
    description: Cool gui
    usage: /<command>
  zeus:
    description: Gives you god hand
    usage: /zeus
